GridLayout:
    cols:4
    rows:3
    padding:10
    Label:
        text: 'I am a Label'
    Button:
        text:'Button 1'
    CheckBox:
        active:True
    Image:
        source:'onepiece.jpg'
    Slider:
        min:-100
        max:100
        value:25
    ProgressBar:
        min:50
        max:100
    TextInput:
        text:'Enter the Text'
    ToggleButton:
        text:'Poetry Mode'
    Switch:
        active:True
