#: import color random
<Text>:
    orientation:'vertical'
    TextInput:
        id:text_input
        font_size:150
        size_hint_y:None
        height:200
        text:'default'
        on_text:my_label.color =[color.random() for i in range(3)]+[1] 
    FloatLayout:
        Scatter:
            Label:
                id:my_label
                text: text_input.text
                font_size:150