<Tab>:
    size_hint:.5,.5
    pos_hint:{'center_x':.5,'center_y':.5}
    do_default_tab:False

    TabbedPanelItem:
        text:'Tab 1'
        Label:
            text:'First tab'
    TabbedPanelItem:
        text:'Tab 2'
        BoxLayout:
            Label:
                text:'Press Button'
            Button:
                text:'click it'
    
    TabbedPanelItem:
        text:'Tab 3'
        RstDocument:
            text:'\n'.join(('How are you'))
